[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "PFD-agent"
dynamic = ["version"]
description = "Agent tools for PFD"
readme = { file = "README.md", content-type = "text/markdown" }
license = { text = "GNU Lesser General Public License v3 (LGPLv3)" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Operating System :: OS Independent"
]
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "dpdata",
    "pydflow>=1.6.57",
    "dargs>=0.4.10",
    "scipy",
    "lbg",
    "periodictable",
    "ase>=3.26.0",
]
[tool.setuptools.packages.find]
where = ["."]
exclude = ["server*"]
