# ========== 必填路径 ==========
db_path: "/tmp/vasp_server/vasp_calculations.db"                    # 数据库文件
structure_path: "/tmp/vasp_server/structures"                        # 从 MP 下载的结构放这里
work_dir: "/tmp/vasp_server/vasp_jobs"                             

# ========== 可选：Materials Project ==========
mp_api_key: ""                                             # 填你的 key，不用就留空

# ========== 重点：默认 INCAR 参数 ==========
VASP_default_INCAR:
  relaxation:
    # 基本控制
    ISTART: 0
    ICHARG: 2
    ENCUT: 520
    PREC: "Accurate"
    EDIFF: 1e-5
    EDIFFG: -0.02

    # 离子步、应力相关
    NSW: 200
    IBRION: 2
    ISIF: 3

    # 费米展宽
    ISMEAR: 0
    SIGMA: 0.05

    # 其他
    LREAL: "Auto"
    LWAVE: false
    LCHARG: false
    ALGO: "Normal"
    ISPIN: 1
    NCORE: 4

  scf_soc:                   # 自洽计算 + 开启自旋轨道耦合
    ISTART: 0
    ICHARG: 2
    ENCUT: 520
    PREC: "Accurate"
    EDIFF: 1e-5

    # 静态计算
    NSW: 0
    IBRION: -1
    ISIF: 2

    # 费米展宽
    ISMEAR: 0
    SIGMA: 0.05

    # 自旋 + SOC
    ISPIN: 2
    GGA: "PE"
    GGA_COMPAT: false
    ISYM: 0

    # 输出与数值细节
    LCHARG: true
    LWAVE: true
    LORBIT: 11
    LASPH: true
    LREAL: "Auto"
    ALGO: "Normal"
    NCORE: 4

  scf_nsoc:                  # 自洽计算，不开 SOC
    ISTART: 0
    ICHARG: 2
    ENCUT: 520
    PREC: "Accurate"
    EDIFF: 1e-5

    # 静态计算：不动原子
    NSW: 0
    IBRION: -1
    ISIF: 2

    # 费米展宽
    ISMEAR: 0
    SIGMA: 0.05

    # 自旋设置
    ISPIN: 1

    # 输出与数值细节
    LCHARG: true
    LWAVE: true
    LORBIT: 11
    LASPH: true
    LREAL: "Auto"
    ALGO: "Normal"
    NCORE: 4

  nscf_nsoc:
    ISTART: 1
    ICHARG: 11
    ENCUT: 520
    PREC: "Accurate"
    EDIFF: 1e-5

    # 静态计算：不动原子
    NSW: 0
    IBRION: -1
    ISIF: 2

    # 费米展宽
    ISMEAR: 0
    SIGMA: 0.05

    # 自旋设置
    ISPIN: 1

    # 输出与数值细节
    LCHARG: false
    LWAVE: false
    LORBIT: 11
    LASPH: true
    LREAL: "Auto"
    ALGO: "Normal"
    NCORE: 4
